name: ci-go-lang-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs: 
  check-application: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: giodou/ci-cd-studies:latest