name: ci-go-lang-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs: 
  check-application: 
    strategy:
      matrix:
        go: ['1.14', '1.15']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
            